services:
  server:
    build: .
    command: >
      sh -c "
      echo 'Waiting for PostgreSQL...' &&
      until pg_isready -h postgres -p 5432 -q; do
        echo 'Waiting for PostgreSQL...';
        sleep 5;
      done &&
      echo 'PostgreSQL is ready!' &&
      alembic upgrade head &&
      uvicorn app.run:app --host 0.0.0.0 --port 8000 --reload
      "
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - network
    ports:
      - "8000:8000"

  postgres:
    image: postgis/postgis:latest
    container_name: postgres_container_tinder
    restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Egor100209"
      POSTGRES_DB: tinder
    networks:
      - network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container_tinder
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5501:80"
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    container_name: pgadmin_container_tinder
    volumes:
      - pgadmin_volume:/var/lib/pgadmin/

networks:
  network:
    driver: bridge

volumes:
  postgres_volume:
  pgadmin_volume:
  redis_data: