"""Enum fix, add active in user

Revision ID: 680b6676bf96
Revises: dd12987b874c
Create Date: 2025-03-04 20:06:10.090214

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680b6676bf96'
down_revision: Union[str, None] = 'dd12987b874c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.execute("DROP INDEX IF EXISTS idx_preferences_location")
    op.create_index('idx_preferences_location', 'preferences', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('preferences', 'longtitude')
    op.drop_column('preferences', 'latitude')
    enum_active = sa.Enum('active', 'inactive', name='active')
    enum_active.create(op.get_bind())

    op.add_column('user', sa.Column('active', enum_active, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.add_column('preferences', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('preferences', sa.Column('longtitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index('idx_preferences_location', table_name='preferences', postgresql_using='gist')
    op.drop_column('preferences', 'location')
    # ### end Alembic commands ###
