"""longitude - longtitude

Revision ID: d8b952189d1e
Revises: dba4e9fcc794
Create Date: 2025-02-23 15:37:14.499792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b952189d1e'
down_revision: Union[str, None] = 'dba4e9fcc794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('longtitude', sa.Float(), nullable=False))
    op.drop_column('preferences', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('preferences', 'longtitude')
    # ### end Alembic commands ###
